### ISSUE TITLE
pin the Linux kernel for bluetooth

### ISSUE THREAD

**Issue by stites** [kvark/dotfiles#1]
Hey! I stumbled on this from your blog post putting nixos on a framework laptop.

You mentioned that you were having trouble with blue tooth from nixos unstable — Have you tried pinning the kernel to a different linuxPackages? It seems like different versions of the kernel do not have the problem you linked in https://bugzilla.kernel.org/show_bug.cgi?id=213829

**Comment by kvark** [comment]
Thank you for visiting my repo!
I haven't tried pinning the kernel packages to lowest. My understanding was that the latest kernel is require for something else, like indicated in https://grahamc.com/blog/nixos-on-framework. Maybe wifi?

**Comment by stites** [comment]
okay! haha -- I don't have a framework laptop but am kicking around the idea and Bluetooth is a requirement for me (so I am wishing you all the luck : ). I have had problems with kernel/firmware support in the past with some boxes and nixos makes this really easy to dabble in.

**Comment by stites** [comment]
closing this!
